import { Container } from "inversify";
import { Application } from "./app";
import { DateController } from "./controllers/date.controller";
import { DifferencesController } from "./controllers/differences-controller";
import { GameCardsController } from "./controllers/game-cards.controller";
import { IndexController } from "./controllers/index.controller";
import { Server } from "./server";
import { DateService } from "./services/date.service";
import { DifferenceCounterService } from "./services/difference-counter.service";
import { DifferencesGeneratorService } from "./services/differences-generator.service";
import { FormValidatorService } from "./services/form-service/form-validator.service";
import { GameCardsService } from "./services/game-cards.service";
import { IndexService } from "./services/index.service";
import { LoginService } from "./services/login.service";
import { WebsocketService } from "./services/websocket.service";
import Types from "./types";

const container: Container = new Container();

container.bind(Types.Server).to(Server);
container.bind(Types.Application).to(Application);
container.bind(Types.IndexController).to(IndexController);
container.bind(Types.IndexService).to(IndexService);
container.bind(Types.DateController).to(DateController);
container.bind(Types.DateService).to(DateService);
container.bind(Types.LoginService).to(LoginService);
container.bind(Types.WebsocketService).to(WebsocketService);
container.bind(Types.GameCardsController).to(GameCardsController);
container.bind(Types.GameCardsService).to(GameCardsService);
container.bind(Types.DifferencesController).to(DifferencesController);
container.bind(Types.DifferenceCounterService).to(DifferenceCounterService);
container.bind(Types.FormValidatorService).to(FormValidatorService);
container.bind(Types.DifferencesGeneratorService).to(DifferencesGeneratorService);
export { container };
