export default {
        Server: Symbol("Server"),
        Application: Symbol("Application"),
        LoginService: Symbol("LoginService"),
        WebsocketService: Symbol("WebsocketService"),
        DifferencesGeneratorService: Symbol("DifferencesGeneratorService"),
        GameCardsController: Symbol("GameCardsController"),
        GameCardsService: Symbol("GameCardsService"),
        DifferencesController: Symbol("DifferencesController"),
        DifferenceCounterService: Symbol("DifferenceCounterService"),
        FormValidator2DService: Symbol("FormValidator2DService"),
        FormValidator3DService: Symbol("FormValidator3DService"),
        BmpFileGenerator: Symbol("BmpFileGenerator"),
        BitmapEncoder: Symbol("BitmapEncoder"),
        DifferenceIdentificator2DService: Symbol("DifferenceIdentificator2DService"),
        DatabaseService: Symbol("DatabaseService"),
        SceneController: Symbol("SceneController"),
        OriginalSceneBuilderService: Symbol("OriginalSceneBuilderService"),
        ModifiedSceneBuilderService: Symbol("ModifiedSceneBuilderService"),
        ScenesParameterGeneratorService: Symbol("ScenesParameterGeneratorService"),
        Scene3DService: Symbol("Scene3DService"),
};
