export default {
        Server: Symbol("Server"),
        Application: Symbol("Application"),
        LoginService: Symbol("LoginService"),
        WebsocketService: Symbol("WebsocketService"),
        DifferencesGeneratorService: Symbol("DifferencesGeneratorService"),
        GameCardsController: Symbol("GameCardsController"),
        GameCardsService: Symbol("GameCardsService"),
        DifferencesController: Symbol("DifferencesController"),
        DifferenceCounterService: Symbol("DifferenceCounterService"),
        FormValidatorService: Symbol("FormValidatorService"),
        BmpFileGenerator: Symbol("BmpFileGenerator"),
        BitmapEncoder: Symbol("BitmapEncoder"),
        BitmapDecoder: Symbol("BitmapDecoder"),
        DifferenceIdentificator2DService: Symbol("DifferenceIdentificator2DService"),
};
